### ISSUE TITLE
HTTP Port should be loaded from a conf file

### ISSUE THREAD

**Issue by doompickaxe** [Web25/http#1]
ATM it is defined in code, but what if the port is already in use. It could be loaded from a conf and still should have a fallback port

**Comment by FelixResch** [comment]
Configuration could be done by using a configurator, that could be assigned to an HTTP Server.

A configurator could read the configuration from an file and use default values for undefined ones. 

**Example Configuration file:**

```
server.port=8080
server.ssl=false
server.http2=true
```

Default Configurations could be:

| Key | Value |
| :-- | :-- |
| server.port | 8080 |
| server.ssl | false |
| server.http2 | false |

**Comment by FelixResch** [comment]
Maybe we could create a class to provide the configuration. The API could look like this.

```kotlin
http.server(Configurator.resource("server.conf"))
```

with an interface like this

```kotlin
interface Configurator {
    fun getInt(name: String): Int
    fun getString(name: String): String
    fun getFile(name: String): File
    ....
}
```
This would eliminate the need for complex toURI() or to toFile() calls when providing a File. You could also use different Configurators, for example clustered configuration from a remote host. 

This is also a big plus for exchangeability.
