### ISSUE TITLE
Proper Cookie Support

### ISSUE THREAD

**Issue by FelixResch** [Web25/http#11]
HTTP Cookies are only implemented on a very basic level. To have more control over cookies on the client a standard compliant implementation is needed.

This would include 

- [x] Adapt the API to support the more complex cases
- [x] Redesign the current cookie model to be able to store standards compliant cookies
- [x] Parsing of cookies in the client code to support all cookie types

**Comment by FelixResch** [comment]
The implementation should be compliant with [RFC 6265](https://tools.ietf.org/html/rfc6265)

**Comment by FelixResch** [comment]
Implementation is now finished, still working on testing the cookie store.

**Comment by FelixResch** [comment]
Another problem appeared during testing: Java 8 Time seems to be unable to parse RFC 1123 datetime formats correctly (especially the timezone part). Maybe we could consider moving to JODA time for time classes?

@doompickaxe whats your opinion on this?

Alternatively we could implement our own parser, because string creation seems to be working just fine...

**Comment by doompickaxe** [comment]
I just heard good things about Joda. Using that library is a good thing, especially if it helps us

**Comment by FelixResch** [comment]
Cookies are now working according to specification and with a new API. Closing this issue
