### ISSUE TITLE
API change for cookies and possibly headers

### ISSUE THREAD

**Issue by FelixResch** [Web25/http#16]
Like @doompickaxe mentioned an API like this would be far more kotlin like and better readable:

```kotlin
val request = http.get("http://example.com/")
request.cookies["hello"] = "world"
```

**Comment by FelixResch** [comment]
API now looks somewhat like this:

Adding a cookie (string, value pair) in response and request

```kotlin
res.cookies["oreo"] = "yummy"
```

Adding a more complex cookie

```kotlin
res.cookies add HttpCookie("oreo", "yummy", path = "/my/stomach")
res.cookies["oreo"] = HttpCookie("oreo", "yummy", path = "/my/stomach")
```

Checking if a cookie exists

```kotlin
if("oreo" in res.cookies) { ... }
```

Iterating over all cookies

```kotlin
res.cookies.forEach { cookie ->
    ....
}
```

Are there any parts of the cookie API that still adaption?

**Comment by doompickaxe** [comment]
You covered everything

**Comment by FelixResch** [comment]
I will also use this API for the http headers, as it is much cleaner and easier to read in kotlin.

Setting headers will look like this:

```kotlin
res.headers["Content-Type"] = "text/html"
```

Getting headers like this:

```kotlin
if(res.headers["Content-Type"] == "text/html") { ... }
```
